FROM python:3-slim
COPY linux-stable-4.9.38 ~/perf
CMD ["/bin/bash"]


#FROM ubuntu:16.04
#COPY perf /usr/local/bin/
#CMD ["/bin/bash"]

#RUN apt-get update && apt-get install -y \
#  linux-tools-generic \
#  linux-tools-4.13.0-43 \
#  vim
#CMD ["/bin/bash"]
