# confguration file defining the data model for influx db logging

#db_drop: false
#db_host: 172.21.20.53
#db_name: riapsdb
#db_password: riapsdevpw
#db_port: 8086
#db_user: riapsdev

# INFLUX CONFIG
influx_logging: False
bucket: mv2
org: scott.r.eisele@vanderbilt.edu
token: xPUdOZETtCeEX3Tn2Lx0UoXmIFUaugMJ-1I6-egVBBPV8ScovBCN4B8FjhgRY7-_4HBxg7J1YW3aGMI48YqoSA==
url: https://us-central1-1.gcp.cloud2.influxdata.com/
