FROM resin/armv7hf-debian

COPY qemu-arm /usr/bin/qemu-arm

#RUN echo Hello from ARM container

#RUN [ "/usr/bin/qemu-arm-static", "/bin/sh", "-c", "/bin/echo Hello from ARM container" ]
CMD ["/bin/bash"]
#CMD ["/bin/sh"]
